[package]
name = "gitcube"
version = "0.1.0"
authors = ["JunWang <1103870790@qq.com>"]
edition = "2018"

[dependencies]
regex = "1"
actix-web = "0.7"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"