[package]
name = "gitcube"
version = "0.1.0"
authors = ["JunWang <1103870790@qq.com>"]
edition = "2018"

[dependencies]
regex = "1"
actix-web = "0.7"
tera = "0.11"
diesel = { version = "1.0.0", features = ["postgres", "sqlite"] }
dotenv = "0.9.0"
serde_json = "1.0"
lazy_static = "1.1.0"